### ISSUE TITLE
After some time the bot gives this error when trying to download whatever song

### ISSUE THREAD

**Issue by NicKoehler** [deethon/deegram#10]
I'm using a fork of this bot, but the error I think you have it too, because also your bot on telegram now it's not working.. here's the trackeback from the log file.

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/telethon/client/updates.py", line 443, in _dispatch_update
    await callback(event)
  File "/app/deegram/plugins/download.py", line 148, in album_playlist_link
    for num, track in enumerate(tracks):
  File "/app/.heroku/src/deethon/deethon/session.py", line 194, in <genexpr>
    tracks = (self.download_track(track, bitrate)
  File "/app/.heroku/src/deethon/deethon/session.py", line 113, in download_track
    track.add_more_tags(self)
  File "/app/.heroku/src/deethon/deethon/types.py", line 287, in add_more_tags
    self.md5_origin = r["DATA"]["MD5_ORIGIN"]
KeyError: 'DATA'
````

Restarting the bot temporary fix the issue.
Seems like the session dies after some time maybe?

**Comment by aykuxt** [comment]
Is your deethon library up to date? (>0.4.3)

**Comment by NicKoehler** [comment]
I use a fork of that too with just the addiction of playlist support.
Can you check your deegram logs too? Just to see if they are the same

**Comment by aykuxt** [comment]
Same error but I am not using the latest version

**Comment by NicKoehler** [comment]
I forked your master and added playlist support, there are more up to date versions?

**Comment by aykuxt** [comment]
master branch should already be the latest one

**Comment by NicKoehler** [comment]
Do you have any ideas of why this happens? I would be glad to help

**Comment by aykuxt** [comment]
I really don't know why the 'DATA' field disappears after some time, the session is refreshed every hour since deethon 0.4.3

**Comment by NicKoehler** [comment]
It doesn't give that error after 1 hour exactly, it seems like random, one time the bot goes 2 days with no problem, and another day it gives that after 3 hour

**Comment by TomyPrs** [comment]
Awesome bot
